num_s: 1.0
weight_s: 1.0
probs_s: 1.5
particle_num: 300
yaw_init: 1.57
odom: 20
alpha_slow_th: 0.001
alpha_fast_th: 0.1
x_cov_init: 0.8
y_cov_init: 0.8
yaw_cov_init: 0.4
x_cov_1: 0.1
y_cov_1: 0.1
yaw_cov_1: 0.05
x_cov_2: 0.01
y_cov_2: 0.01
yaw_cov_2: 0.01
limit: 100
move_noise: 0.2
estimated_weight_th: 4.0
roomba_odom: roomba_only_odom
is_only_odom: true
